### ISSUE TITLE
ValueError: Expected 484916 peptide predictions but got 267878

### ISSUE THREAD

**Issue by ihodes** [openvax/topiary#70]
traceback:
```
Topiary commandline arguments:
Namespace(genome=None, ic50_cutoff=500.0, json_variants=[], maf=[], mhc_alleles='', mhc_alleles_file='/pgv-results/biokepi-coco-work/work/LLC-A9F1-no-stim-mm10/e7d473802c15aedaf66dcbc994e98bedH-2-KbH-2-DbMHC_allleles.txt', mhc_epitope_lengths=[8, 9, 10, 11], mhc_peptide_lengths=None, mhc_predictor='netmhccons', only_novel_epitopes=False, output_csv='/pgv-results/biokepi-coco-work/work/LLC-A9F1-no-stim-mm10/bb09754c50c2021ded5f9a3f6200182bnetmhcconsdefaulte7d473802c15aedaf66dcbc994e98bedH-2-KbH-2-DbMHC_alllelestopiary.tsv', output_csv_sep=',', output_html=None, padding_around_mutation=None, percentile_cutoff=2.0, print_columns=False, rename_output_column=None, rna_gene_fpkm_tracking_file=None, rna_min_gene_expression=4.0, rna_min_transcript_expression=1.5, rna_transcript_fpkm_gtf_file=None, rna_transcript_fpkm_tracking_file=None, skip_variant_errors=False, subset_output_columns=None, variant=[], vcf=['/pgv-results/biokepi-coco-work/work/LLC-A9F1-no-stim-mm10/2bbce8348335025f679e2d861002d46601884e17533a3151fe3f289d55003433cd0c2cfaa8fee33f405d4810fc312e98mark_dups-1-6182dba5aec-indelreal-mergeddefaultdefaultgatk_bqsr_strelka-exome-defaultstrelka_output/results/passed_somatic_combined.vcf', '/pgv-results/biokepi-coco-work/work/LLC-A9F1-no-stim-mm10/45dc4061f7fe7fdf657f2bd4c34e503b01884e17533a3151fe3f289d55003433cd0c2cfaa8fee33f405d4810fc312e98mark_dups-1-6182dba5aec-indelreal-mergeddefaultdefaultgatk_bqsr_mutect-default_without_cosmic-merged.vcf'], wildtype_ligandome_directory=None)
Traceback (most recent call last):
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/bin/topiary", line 58, in <module>
    main(args)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/bin/topiary", line 43, in main
    epitopes = predict_epitopes_from_args(args)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/topiary/predict_epitopes.py", line 294, in predict_epitopes_from_args
    raise_on_variant_effect_error=not args.skip_variant_errors)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/topiary/predict_epitopes.py", line 261, in predict_epitopes_from_variants
    wildtype_ligandome_dict=wildtype_ligandome_dict)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/topiary/predict_epitopes.py", line 157, in predict_epitopes_from_mutation_effects
    binding_predictions = mhc_model.predict(protein_subsequences)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/mhctools/base_predictor.py", line 150, in predict
    return self.predict_subsequences(sequence_dict, peptide_lengths=None)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/mhctools/base_predictor.py", line 133, in predict_subsequences
    binding_predictions = self.predict_peptides(sorted(peptide_set))
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/mhctools/base_commandline_predictor.py", line 319, in predict_peptides
    n_expected=len(peptides) * len(self.alleles))
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/topiary.1.2.0/lib/python3.6/site-packages/mhctools/base_predictor.py", line 105, in _check_result_count
    n_expected, len(binding_predictions)))
```

**Comment by iskandr** [comment]
Latest mhctools should at least give us some insight on which peptides are missing.
